### ISSUE TITLE
GET body not allowed

### ISSUE THREAD

**Issue by idabic** [MaxCDN/python-maxcdn#8]
I was working on debugging one reported issue with python fetching raw logs via API and found that you are missing definition in get method for body:

def get(self, end_point, *_kwargs):
       return self.client.get(self._get_url(end_point),
               headers=self._get_headers(json=False),
               *_kwargs).json()

should contain "data=None":

def get(self, end_point, data=None, *_kwargs):
       return self.client.get(self._get_url(end_point),
               headers=self._get_headers(json=False),
               *_kwargs).json()

otherwise, exception is thrown as:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/maxcdn/maxcdn.py", line 40,
in get
    *_kwargs).json()
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 468,
in get
    return self.request('GET', url, *_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 422,
in request
    prep = self.prepare_request(req)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 360,
in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 298, in
prepare
    self.prepare_auth(auth, url)
  File "/usr/lib/python2.7/dist-packages/requests/models.py", line 475, in
prepare_auth
    r = auth(self)
  File
"/usr/local/lib/python2.7/dist-packages/requests_oauthlib/oauth1_auth.py",
line 79, in **call**
    unicode(r.url), unicode(r.method), r.body or '', r.headers)
  File
"/usr/local/lib/python2.7/dist-packages/oauthlib/oauth1/rfc5849/**init**.py",
line 287, in sign
    raise ValueError('GET/HEAD requests should not include body.')
ValueError: GET/HEAD requests should not include body.

**Comment by jmervine** [comment]
@idabic Is this issue still valid for you?
